version: "3"

services: 
    project:
        build: 
            context: .
            dockerfile: ./docker/app.Dockerfile
        ports: 
         - "8080:8080"
        env_file: 
            - ./prod-env.sh
        depends_on: 
            - database
        networks: 
            - defaultnet    
    database:
        build: 
            context: .
            dockerfile: ./docker/db.Dockerfile
        ports: 
            - "5432:5432"
        networks: 
            - defaultnet
networks: 
    defaultnet:
