version: "3"

services: 
    database-dev:
        image: postgres:12-alpine
        volumes: 
            - ./data/all_files.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_DB=${DB_DATABASE}
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports: 
            - "5432:5432"